# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a196108fc47edaefe26833d260c66b907164fc554b9d48e72aad1133d73e5097abe4105f728eb8593e2ad99ed2e6daf3985e69ac4dab680fc2c2f3d5d10e419b

test:
  secret_key_base: c69d5698e0073ffe52e1277cb2aeb45d451ce435f1017f37cb5978bdd3a5326d45e0042e50f46c57dbb1d235242fbd96be1e5c5710b9dc46310fd3ed63234784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
