# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 29) do

  create_table "account_games", :force => true do |t|
    t.column "game_id",    :integer
    t.column "account_id", :integer
    t.column "created_at", :datetime
    t.column "origin",     :text
    t.column "price",      :float
    t.column "transdate",  :datetime
    t.column "shield",     :boolean
  end

  create_table "accounts", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "authors", :force => true do |t|
    t.column "name",    :string
    t.column "surname", :string
  end

  create_table "authorships", :force => true do |t|
    t.column "author_id", :integer
    t.column "game_id",   :integer
  end

  create_table "game_extensions", :force => true do |t|
    t.column "game_id",      :integer
    t.column "extension_id", :integer
  end

  create_table "game_photos", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "game_id",      :integer
  end

  create_table "games", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "difficulty",   :integer,  :default => 1
    t.column "min_player",   :integer,  :default => 1
    t.column "max_player",   :integer
    t.column "price",        :float
    t.column "time_average", :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "publish_year", :string
    t.column "editor",       :string
    t.column "url",          :text
    t.column "average",      :float,    :default => 0.0
  end

  create_table "parties", :force => true do |t|
    t.column "game_id",    :integer
    t.column "created_at", :datetime
    t.column "account_id", :integer
  end

  create_table "players", :force => true do |t|
    t.column "name",       :text
    t.column "nickname",   :text
    t.column "account_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"

end
